modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="clockhud" #mandatory
version="2.0.0" #mandatory
displayName="Clock HUD" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
credits="Created by QKninja" #optional
authors="QKninja" #optional
description='''
    A simple clock GUI to check the time.
'''

[[dependencies.clockhud]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.clockhud]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
